#!/opt/homebrew/bin/fish

if test (count $argv) -ge 2
    switch $argv[1]
        case '-t' # transparency
            if test $argv[2] = '-d'
                set transparencyValue 0.2
                osascript ~/Developer/scripts/applescript/iterm2/transparency.scpt $transparencyValue
            else
                set transparencyValue $argv[2]
                osascript ~/Developer/scripts/applescript/iterm2/transparency.scpt $transparencyValue
            end
        case '*'
            echo "Usage: iterm -t <transparency_value>"
            return 1
    end
else
    # Print usage if incorrect number of arguments
    echo "Usage: iterm -t <transparency_value> | iterm -t -d"
    return 1
end

