#!/opt/homebrew/bin/fish

# Check if the first argument is '-t'
if test (count $argv) -eq 2
    switch $argv[1]
        case '-t'
            # Get the transparency value from the second argument
            set transparencyValue $argv[2]
            
            # Run the AppleScript with the transparency value
            osascript ~/Developer/scripts/applescript/iterm2/transparency.scpt $transparencyValue
        case '*'
            # If not '-t', just print an error message or handle other cases
            echo "Usage: iterm -t <transparency_value>"
            return 1
    end
else
    # Print usage if incorrect number of arguments
    echo "Usage: iterm -t <transparency_value>"
    return 1
end
